<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.UEFS.vaiJunto</groupId>
    <artifactId>vaiJunto-parent</artifactId>
    <version>1.5</version>
  </parent>

  <artifactId>Client</artifactId>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <junit.version>5.12.1</junit.version>  </properties>

  <dependencies>
    <dependency>
      <groupId>org.UEFS.vaiJunto</groupId>
      <artifactId>Shared</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.UEFS.custom</groupId>
      <artifactId>Custom</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-controls</artifactId>
    </dependency>
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-fxml</artifactId>
    </dependency>

    <dependency>
      <groupId>org.controlsfx</groupId>
      <artifactId>controlsfx</artifactId>
      <version>11.2.1</version>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-maven-plugin</artifactId>
        <configuration>
          <mainClass>org.UEFS.vaijunto.client.AppLauncher</mainClass>
          <options>
            <option>--add-opens=java.base/sun.misc=ALL-UNNAMED</option>
            <option>--enable-native-access=ALL-UNNAMED</option>
          </options>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>