services:
  server:
    build:
      context: .
      dockerfile: Docker/Server/Dockerfile
    container_name: vai-junto-server
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - .:/app
      - ./data:/app/data
      - maven-cache:/root/.m2

  client:
    build:
      context: .
      dockerfile: Docker/Client/Dockerfile
    container_name: vai-junto-client
    volumes:
      - .:/app
      - ./data:/app/data
      - maven-cache:/root/.m2
    environment:
      SERVER_IP: "172.16.230.27"
      SERVER_PORT: "2602"

volumes:
  maven-cache: