services:
  server:
    build:
      context: .
      dockerfile: Docker/Server/Dockerfile
    container_name: vai-junto-server
    init: true
    stop_grace_period: 30s
    ports:
      - "2602:2602"
    tty: true
    volumes:
      - .:/app
      - ./data:/app/data
      - maven-cache:/root/.m2

  client:
    build:
      context: .
      dockerfile: Docker/Client/Dockerfile
    container_name: vai-junto-client
    volumes:
      - .:/app
      - ./data:/app/data
      - maven-cache:/root/.m2
    environment:
      SERVER_IP: "10.65.137.41"
      SERVER_PORT: "2602"

volumes:
  maven-cache: